export const userConstants = {
    GET_ALL_USER_DATA_REQUEST: "GET_ALL_USER_DATA_REQUEST",
    GET_ALL_USER_DATA_SUCCESS: "GET_ALL_USER_DATA_SUCCESS",
    GET_ALL_USER_DATA_FAILURE: "GET_ALL_USER_DATA_FAILURE",

    DELETE_USER: "DELETE_USER",

    SEARCH_USER_REQUEST: "SEARCH_USER_REQUEST",
    SEARCH_USER_SUCCESS: "SEARCH_USER_SUCCESS",
    SEARCH_USER_FAILURE: "SEARCH_USER_FAILURE",

    SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
    SET_SORT_ORDER: "SET_SORT_ORDER",
};
